### ISSUE TITLE
[Saldo] Mostrar cantidad de comidas posibles 

### ISSUE THREAD

**Issue by KaySoohyun** [AIDEA775/UNCmorfi#28]
Junto con el saldo podria decir cuantas raciones podes comprar con la carga actual de la tarjeta.
Deberia ponerse en rojo cuando queden cuatro raciones disponibles.
Debe tener en cuenta el tipo de usuario y el valor de la racion segun el mismo.

**Comment by AIDEA775** [comment]
Como que no entra en la UI, no?

**Comment by AIDEA775** [comment]
5 años y 12 días despues: Se hizo xD
