### ISSUE TITLE
Pasarla en tarjeta de memoria

### ISSUE THREAD

**Issue by NicolasHorMann** [AIDEA775/UNCmorfi#32]
Que la aplicación pueda ponerse en la tarjeta de memoria en lugar de consumir almacenamiento del dispositivo.

**Comment by AIDEA775** [comment]
Jejox, lo había puesto en el lugar incorrecto. #8 

En el emulador de Android 4.4 ahora me sale la opción para mover la app a la SD, pero no en el emulador de Android 7.1, no tengo idea de porqué pero espero que sea cuestion del emulador (dejo el issue abierto hasta que lo pueda comprobar).
